### ISSUE TITLE
Fix assembly scheme for NoC with topology of columns.

### ISSUE THREAD

**Issue by jessebarreto** [jessebarreto/NetworkOnChip#8]
When the NoC has a width of one, the connections between the rows are always horizontal.

**Comment by jpassos92** [comment]
main.cpp, line 90

connectRouters(*routers.at(i), *routers.at(i + j), *channel, j == 1);

**Comment by jpassos92** [comment]
Check the main.cpp in my branch, its propably fixed. I simplified the current logic. Now we assume that the first router, AKA R0, do not make any connection, and starting from the router R1 we check if there is need to make a connection to their left-side and up-side routers, should them exist and respecting the desired topology.
